services:
  whatsmyip-dual:
    image: whatsmyip-dual:latest
    container_name: whatsmyip-dual
    network_mode: host
    environment:
      - TZ=Europe/Paris
      - IP_MODE=both
      - PORT=3464
    restart: unless-stopped
